name: generate animation and wakatime

on:
  schedule:
    - cron: "0 16 * * *" 
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit github-contribution-grid-snake.svg
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update github-contribution-grid-snake.svg
          file_pattern: dist/github-contribution-grid-snake.svg

  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: True
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_PROJECTS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          SHOW_LANGUAGE: False